name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: |
          lib/libcitro3d.a
          lib/libcitro3dd.a
